#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2012 OpenWrt.org

START=60

SERVICE_USE_PID=1

start() {
	[ -f /etc/monitrc ] || return 1
	ls -l /etc/monitrc | grep -q '^-rw-------'
    [ $? -eq 0 ] || chmod 0700 /etc/monitrc
	service_start /usr/bin/monit
}

stop() {
	service_stop /usr/bin/monit
}
